// Sample error-tracking data for the Logs / error-tracking stories.
import type { Issue } from "../../components/errors";

const ago = (min: number) => new Date(Date.now() - min * 60000).toISOString();
const freq = (seed: number) => Array.from({ length: 24 }, (_, i) => Math.max(0, Math.round(8 + Math.sin((i + seed) / 2.5) * 7 + ((i * seed) % 5))));

export const SAMPLE_ISSUES: Issue[] = [
  {
    id: "1",
    title: "TypeError: Cannot read properties of undefined (reading 'id')",
    culprit: "app/checkout/page.tsx in handleSubmit",
    level: "error",
    count: 1284,
    userCount: 342,
    firstSeen: ago(60 * 26),
    lastSeen: ago(3),
    status: "unresolved",
    environment: "production",
    assignee: { name: "Fady Mondy", email: "fady@example.com" },
    frequency: freq(1),
    tags: [
      { key: "browser", value: "Chrome 138" },
      { key: "os", value: "macOS 15" },
      { key: "release", value: "v0.20.1" },
      { key: "url", value: "/checkout" },
    ],
    stack: [
      { filename: "app/checkout/page.tsx", function: "handleSubmit", lineno: 84, colno: 21, inApp: true, context: [
        { line: 82, text: "  const order = await createOrder(cart);" },
        { line: 83, text: "  // order may be null when the cart expired" },
        { line: 84, text: "  trackPurchase(order.id, total);", current: true },
        { line: 85, text: "  router.push(`/orders/${order.id}`);" },
      ] },
      { filename: "lib/forms/useSubmit.ts", function: "onSubmit", lineno: 31, inApp: true },
      { filename: "node_modules/react-dom/cjs/react-dom.production.js", function: "invokeGuardedCallback", lineno: 4213 },
    ],
    breadcrumbs: [
      { timestamp: ago(4), category: "navigation", type: "navigation", message: "Navigated to /checkout" },
      { timestamp: ago(4), category: "ui.click", type: "ui", message: 'Clicked button "Place order"' },
      { timestamp: ago(3), category: "http", type: "http", message: "POST /api/orders → 200 (412ms)" },
      { timestamp: ago(3), category: "exception", type: "error", message: "TypeError thrown", level: "error" },
    ],
  },
  {
    id: "2",
    title: "FatalError: Database connection pool exhausted",
    culprit: "internal/db/pool.go in Acquire",
    level: "fatal",
    count: 47,
    userCount: 47,
    firstSeen: ago(60 * 5),
    lastSeen: ago(12),
    status: "unresolved",
    environment: "production",
    frequency: freq(4),
    tags: [{ key: "service", value: "api" }, { key: "region", value: "eu-west-1" }],
    stack: [
      { filename: "internal/db/pool.go", function: "Acquire", lineno: 142, inApp: true, context: [
        { line: 141, text: "select {" },
        { line: 142, text: "case <-ctx.Done(): return nil, ErrPoolExhausted", current: true },
        { line: 143, text: "}" },
      ] },
    ],
  },
  {
    id: "3",
    title: "Unhandled Promise Rejection: NetworkError when attempting to fetch resource",
    culprit: "lib/api/client.ts in request",
    level: "warning",
    count: 903,
    userCount: 211,
    firstSeen: ago(60 * 50),
    lastSeen: ago(28),
    status: "unresolved",
    environment: "production",
    assignee: { name: "Omar", email: "omar@example.com" },
    frequency: freq(7),
    tags: [{ key: "browser", value: "Safari 18" }, { key: "connection", value: "4g" }],
  },
  {
    id: "4",
    title: "ValidationError: password must be at least 8 characters",
    culprit: "app/(auth)/register/page.tsx",
    level: "info",
    count: 5120,
    userCount: 1890,
    firstSeen: ago(60 * 120),
    lastSeen: ago(1),
    status: "ignored",
    environment: "production",
    frequency: freq(2),
  },
  {
    id: "5",
    title: "RangeError: Maximum call stack size exceeded",
    culprit: "components/Tree.tsx in renderNode",
    level: "error",
    count: 76,
    userCount: 19,
    firstSeen: ago(60 * 9),
    lastSeen: ago(140),
    status: "resolved",
    environment: "staging",
    frequency: freq(5),
  },
];
